name: CI Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-crud

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src --no-warnings

      - name: Run tests
        run: npm test

      - name: Performance test (basic)
        run: echo "Simulación básica de performance completada"

      - name: Success message
        if: success()
        run: echo "Todas las pruebas se ejecutaron correctamente."
