name: CI Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    defaults:
      run:
        working-directory: backend-crud

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src --no-warnings

      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017/product-db-test
        run: npm test

      - name: Performance test (basic)
        run: echo "Simulación básica de performance completada"

      - name: Success message
        if: success()
        run: echo "Todas las pruebas se ejecutaron correctamente."
